/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoDesarrolloSoftware;

import javax.swing.JComboBox;

/**
 *
 * @author Guillermo
 */
public class Form_Peso extends javax.swing.JFrame {
        double conversionPeso = 0, Peso = 0, total = 0, kg = 2.20462;
        String libra = "LIBRAS A KILOGRAMOS", kilo = "KILOGRAMOS A LIBRAS";
    
    public Form_Peso() {
        initComponents();
        this.setLocationRelativeTo(null);// CENTRAR FORM
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        left_panel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btnLongitud = new javax.swing.JButton();
        btnRegresarr = new javax.swing.JButton();
        btnGotas = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnVolumen = new javax.swing.JButton();
        right_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtPeso = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbPeso = new javax.swing.JComboBox<>();
        btnCalcular = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONVERSIONES");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left_panel.setBackground(new java.awt.Color(46, 134, 193));
        left_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        left_panel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 250, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONVERSIONES");
        left_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 280, 40));

        btnLongitud.setBackground(new java.awt.Color(93, 173, 226));
        btnLongitud.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLongitud.setForeground(new java.awt.Color(255, 255, 255));
        btnLongitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pies-metrosXxX.jpg"))); // NOI18N
        btnLongitud.setText(" LONGITUD");
        btnLongitud.setBorder(null);
        btnLongitud.setBorderPainted(false);
        btnLongitud.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLongitud.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLongitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLongitudActionPerformed(evt);
            }
        });
        left_panel.add(btnLongitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 270, 50));

        btnRegresarr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegresarr.setForeground(new java.awt.Color(0, 51, 102));
        btnRegresarr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/HOME_1.png"))); // NOI18N
        btnRegresarr.setBorderPainted(false);
        btnRegresarr.setContentAreaFilled(false);
        btnRegresarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarrActionPerformed(evt);
            }
        });
        left_panel.add(btnRegresarr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        btnGotas.setBackground(new java.awt.Color(93, 173, 226));
        btnGotas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGotas.setForeground(new java.awt.Color(255, 255, 255));
        btnGotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/GOTA AGUA PNG 35X35_1.png"))); // NOI18N
        btnGotas.setText("CÁLCULO DE GOTAS");
        btnGotas.setBorder(null);
        btnGotas.setBorderPainted(false);
        btnGotas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGotas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGotasActionPerformed(evt);
            }
        });
        left_panel.add(btnGotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 270, 50));

        jButton4.setBackground(new java.awt.Color(93, 173, 226));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LIBRA A KILOS PNG.png"))); // NOI18N
        jButton4.setText(" PESO");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        left_panel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 270, 50));

        btnVolumen.setBackground(new java.awt.Color(93, 173, 226));
        btnVolumen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVolumen.setForeground(new java.awt.Color(255, 255, 255));
        btnVolumen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/litros-A-mililitrosXxX_1.jpg"))); // NOI18N
        btnVolumen.setText(" VOLUMEN");
        btnVolumen.setBorder(null);
        btnVolumen.setBorderPainted(false);
        btnVolumen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVolumen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVolumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolumenActionPerformed(evt);
            }
        });
        left_panel.add(btnVolumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 270, 50));

        bg.add(left_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 610));

        right_panel.setBackground(new java.awt.Color(255, 255, 255));
        right_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Perder-peso wallpaper.jpg"))); // NOI18N
        right_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 520, 270));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Conversiones de Peso: Libras - Kilogramos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPeso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPeso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 190, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("Total:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        cmbPeso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione>", "LIBRAS A KILOGRAMOS", "KILOGRAMOS A LIBRAS" }));
        cmbPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPesoActionPerformed(evt);
            }
        });
        jPanel1.add(cmbPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 180, 30));

        btnCalcular.setBackground(new java.awt.Color(31, 97, 141));
        btnCalcular.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, 40));

        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 280, 40));

        jLabel3.setText("Ingrese el valor a convertir:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        right_panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 490, 300));

        bg.add(right_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 520, 590));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarrActionPerformed
        this.dispose();//cierra el formualrio sin salir del programa
    }//GEN-LAST:event_btnRegresarrActionPerformed

    private void btnGotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGotasActionPerformed
        FormConversion c = new FormConversion();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGotasActionPerformed

    private void btnVolumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolumenActionPerformed
        Form_Volumen v = new Form_Volumen();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolumenActionPerformed

    private void btnLongitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLongitudActionPerformed
        Form_Longitud l = new  Form_Longitud();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLongitudActionPerformed

    private void cmbPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPesoActionPerformed
        JComboBox cb = (JComboBox)evt.getSource();
        String opcionGota = (String) cb.getSelectedItem();
        
        if (opcionGota.contentEquals(libra))
            conversionPeso = 1;
        else if (opcionGota.contentEquals(kilo))
             conversionPeso = 0;
    }//GEN-LAST:event_cmbPesoActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        Peso = Double.parseDouble(txtPeso.getText());
       
        if(conversionPeso == 1){
            total = Peso * (1 / 2.20462);
        }
        else if(conversionPeso == 0){
            total = Peso * (2.20462 / 1);
        } 
        
        txtTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Peso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Peso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Peso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Peso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Peso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnGotas;
    private javax.swing.JButton btnLongitud;
    private javax.swing.JButton btnRegresarr;
    private javax.swing.JButton btnVolumen;
    private javax.swing.JComboBox<String> cmbPeso;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel left_panel;
    private javax.swing.JPanel right_panel;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
