/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoDesarrolloSoftware;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Guillermo
 */
public class FormREGISTRO extends javax.swing.JFrame {

    /**
     * Creates new form FormREGISTRO
     */
    public FormREGISTRO() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
     public Image getIconImage(){//codigo para cambiar de icono de la app
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("image/iconoDoctor.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuRegistro = new javax.swing.JMenuItem();
        mnuConversion = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/medicalFONDO_1.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 530));

        jMenu1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Patient_Male_icon-iconsverga.png"))); // NOI18N
        jMenu1.setText("PACIENTES");

        mnuRegistro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        mnuRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/y.png"))); // NOI18N
        mnuRegistro.setText("Registro de Atención");
        mnuRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegistroActionPerformed(evt);
            }
        });
        jMenu1.add(mnuRegistro);

        mnuConversion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mnuConversion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/xy.png"))); // NOI18N
        mnuConversion.setText("Conversiones");
        mnuConversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConversionActionPerformed(evt);
            }
        });
        jMenu1.add(mnuConversion);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/salirICON.png"))); // NOI18N
        jMenu2.setText("SALIR");

        mnuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        mnuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoSALIR.png"))); // NOI18N
        mnuExit.setText("Finalizar el Programa");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        jMenu2.add(mnuExit);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
       JOptionPane.showMessageDialog(null, "¡ADIOS!", "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_mnuExitActionPerformed

    private void mnuConversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConversionActionPerformed
     FormConversion x = new FormConversion();
     x.setVisible(true);  
    }//GEN-LAST:event_mnuConversionActionPerformed

    private void mnuRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegistroActionPerformed
     //JOptionPane.showMessageDialog(null, "A Ingresado a Registro de Atencion", "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
     RegistroAtencion v = new RegistroAtencion();
     v.setVisible(true);
    }//GEN-LAST:event_mnuRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormREGISTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormREGISTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormREGISTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormREGISTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormREGISTRO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuConversion;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuRegistro;
    // End of variables declaration//GEN-END:variables
}
